web/tv/urls.py
from django.urls import path, include
from .views import ServersList, ServersAdd, ServersEdit, ServersDelete, ServersTest
from .views import ChannelsList, ChannelsAdd, ChannelsEdit, ChannelsDelete, ChannelsControl

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', ChannelsList.as_view()),
    path('servers/', ServersList.as_view()),
    path('servers/new/', ServersAdd.as_view()),
    path('servers/<int:pk>/', ServersEdit.as_view()),
    path('servers/<int:pk>/delete/', ServersDelete.as_view()),
    path('servers/<int:pk>/test/', ServersTest.as_view()),
    path('channels/', ChannelsList.as_view()),
    path('channels/new/', ChannelsAdd.as_view()),
    path('channels/<int:pk>/', ChannelsEdit.as_view()),
    path('channels/<int:pk>/delete/', ChannelsDelete.as_view()),
    path('channels/<int:pk>/<str:action>/', ChannelsControl.as_view()),
]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

web/web/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import RedirectView
from tv.views import Live


urlpatterns = [
    path('', Live.as_view()),
    path('login', LoginView.as_view(template_name='tv/control/login/login.html')),
    path('login/', LoginView.as_view(template_name='tv/control/login/login.html')),
    path('logout', LogoutView.as_view()),
    path('logout/', LogoutView.as_view()),
    path('admin/', admin.site.urls),
    path('control', include('tv.urls')),
    path('control/', include('tv.urls')),
]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

web/tv/models.py
from django.db import models

SOURCE_TYPES = [
    ('Generic', 'Generic'),
    ('YouTube', 'YouTube')
]

CODEC_CHOICES = [
    ('copy', 'Copy source'),
    ('libx264 -preset ultrafast -crf 23', 'x264 ultrafast CRF23 (Default)'),
    ('libx264 -preset ultrafast -crf 10', 'x264 ultrafast CRF10 (Highest Q)'),
    ('libx264 -preset ultrafast -crf 15', 'x264 ultrafast CRF15 (High Q)'),
    ('libx264 -preset ultrafast -crf 30', 'x264 ultrafast CRF30 (Low Q)'),
    ('libx264 -preset ultrafast -crf 35', 'x264 ultrafast CRF35 (Lowest Q)'),
]


class Server(models.Model):
    name = models.CharField(max_length=128)
    address = models.CharField(max_length=128)
    api_port = models.CharField(max_length=5)
    username = models.CharField(max_length=128, blank=True, null=True)
    password = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return self.name


class Channel(models.Model):
    name = models.CharField(max_length=128)
    source = models.CharField(max_length=2048)
    source_type = models.CharField(
        max_length=128, default='Generic', choices=SOURCE_TYPES)
    codec = models.CharField(
        max_length=128, default='copy', choices=CODEC_CHOICES)
    logo = models.ImageField(upload_to="logos", null=True)
    server = models.ForeignKey(Server, on_delete=models.PROTECT)

    def __str__(self):
        return self.name

web/tv/forms.py
from django.forms import ModelForm, FileInput
from .models import Server, Channel


class ServerForm (ModelForm):
    class Meta:
        model = Server
        fields = '__all__'


class ChannelForm (ModelForm):
    class Meta:
        model = Channel
        fields = '__all__'
        widgets = {
            'logo': FileInput()
        }

web/tv/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.views.generic import TemplateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Server, Channel
from .modules import docker_control


class Live(View):
    def get(self, request, *args, **kwargs):
        channels = Channel.objects.all().order_by('name')
        context = {
            "channels": channels,
        }
        return render(request, 'tv/player/player.html', context=context)


class ServersList(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        servers = Server.objects.all()
        context = {
            "servers": servers,
        }
        return render(request, "tv/control/servers/list.html", context=context)


class ServersAdd(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        from .forms import ServerForm
        form = ServerForm
        context = {
            "form": form,
        }
        return render(request, "tv/control/servers/add.html", context=context)

    def post(self, request, *args, **kwargs):
        from .forms import ServerForm
        form = ServerForm(request.POST)
        if form.is_valid():
            form.save()
            context = {
                "message": "Server "+form.data['name']+" added",
            }
            return redirect(to="../")
        else:
            context = {
                "form": form,
            }
            return render(request, "tv/control/servers/edit.html", context=context)


class ServersEdit(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        from .forms import ServerForm
        server = get_object_or_404(Server, pk=self.kwargs["pk"])
        form = ServerForm(instance=server)
        context = {
            "form": form,
        }
        return render(request, "tv/control/servers/edit.html", context=context)

    def post(self, request, *args, **kwargs):
        from .forms import ServerForm
        server = get_object_or_404(Server, pk=self.kwargs['pk'])
        form = ServerForm(request.POST, instance=server)
        if form.is_valid():
            form.save()
            return redirect(to="../")
        else:
            context = {
                "form": form,
            }
            return render(request, "tv/control/servers/edit.html", context=context)


class ServersDelete(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        from .forms import ServerForm
        server = get_object_or_404(Server, pk=self.kwargs['pk'])
        form = ServerForm(request.POST, instance=server)
        context = {
            "server": server,
            "form": form,
        }
        return render(request, "tv/control/servers/delete.html", context=context)

    def post(self, request, *args, **kwargs):
        server = get_object_or_404(Server, pk=self.kwargs['pk'])
        server.delete()
        return redirect(to="/control/servers/")


class ServersTest(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        server = get_object_or_404(Server, pk=self.kwargs['pk'])
        import docker
        docker_url = "http://"+server.address+":"+server.api_port
        client = docker.DockerClient(base_url=docker_url)
        try:
            info = client.info()
            context = {
                "server": server,
                "info": info,
            }
            return render(request, "tv/control/servers/test.html", context=context)
        except:
            context = {
                "server": server,
                "message": "Failed to establish a new connection to "+docker_url,
            }
            return render(request, "tv/control/servers/test.html", context=context)


class ChannelsList(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        channels = Channel.objects.all().order_by('name')
        from .modules import docker_control
        for channel in channels:
            try:
                client = docker_control.Client(channel)
                channel.container = client.get_container()
            except:
                channel.container = "Not found !"
        context = {
            "channels": channels,
        }
        return render(request, "tv/control/channels/list.html", context=context)


class ChannelsAdd(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        from .forms import ChannelForm
        form = ChannelForm
        context = {
            "form": form,
        }
        return render(request, "tv/control/channels/add.html", context=context)

    def post(self, request, *args, **kwargs):
        from .forms import ChannelForm
        form = ChannelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            channels = Channel.objects.all()
            context = {
                "channels": channels,
            }
            return redirect(to="../")
        else:
            context = {
                "form": form,
            }
            return render(request, "tv/control/channels/edit.html", context=context)


class ChannelsEdit(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        from .forms import ChannelForm
        channel = get_object_or_404(Channel, pk=self.kwargs["pk"])
        form = ChannelForm(instance=channel)
        context = {
            "form": form,
        }
        return render(request, "tv/control/channels/edit.html", context=context)

    def post(self, request, *args, **kwargs):
        from .forms import ChannelForm
        channel = get_object_or_404(Channel, pk=self.kwargs["pk"])
        client = docker_control.Client(channel)

        form = ChannelForm(request.POST, request.FILES, instance=channel)

        if form.is_valid():
            client.rename_channel(name=form.data['name'])
            form.save()
            return redirect(to="../")
        else:
            context = {
                "form": form,
            }
            return render(request, "tv/control/channels/edit.html", context=context)


class ChannelsDelete(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        from .forms import ChannelForm
        channel = get_object_or_404(Channel, pk=self.kwargs["pk"])
        form = ChannelForm(request.POST, instance=channel)
        context = {
            "channel": channel,
            "form": form,
        }
        return render(request, "tv/control/channels/delete.html", context=context)

    def post(self, request, *args, **kwargs):
        channel = get_object_or_404(Channel, pk=self.kwargs['pk'])
        client = docker_control.Client(channel)
        client.delete_channel()
        channel.delete()
        return redirect(to="/control/channels/")


class ChannelsControl(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        channel = get_object_or_404(Channel, pk=self.kwargs["pk"])
        action = self.kwargs["action"]

        client = docker_control.Client(channel)

        if client.connected:

            if action == "start":
                client.start_channel()
            if action == "stop":
                client.stop_channel()
            if action == "restart":
                client.restart_channel()
            if action == "recreate":
                client.recreate_channel()
            if action == "stats":
                stats = client.get_stats()

        return redirect(to="/control/channels/")

web/tv/templates/tv/control/channels/add.html
{% extends "tv/control/base.html" %}

{% block content %}
<div class="col-6">
    <div class="row">
        <h3>Add new channel</h3>
    </div>
    <div class="row">
        <div class="card is-full-width">
            <form id="form" method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Add" class="button primary">
                <input type="button" value="Cancel" onClick="location='{{ request.META.HTTP_REFERER }}'"
                    class="button dark">
        </div>
    </div>
</div>
</div>
{% endblock content %}

web/tv/templates/tv/control/channels/delete.html
{% extends "tv/control/base.html" %}

{% block content %}
<div class="col-6">
    <div class="row">
        <h3>Are you sure ?</h3>
    </div>
    <div class="row">
        <div class="card is-full-width">
            <h4>Delete channel {{ channel }}</h4>
            <form id="form" method="post">
                {% csrf_token %}
                <input type="submit" value="Yes" class="button primary">
                <input type="button" value="Cancel" onClick="location='{{ request.META.HTTP_REFERER }}'" class="button dark">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

web/tv/templates/tv/control/channels/edit.html
{% extends "tv/control/base.html" %}

{% block content %}
<div class="col-6">
    <div class="row">
        <h3>Edit channel</h3>
    </div>
    <div class="row">
        <div class="card is-full-width">
            <form id="form" method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Save" class="button">
                <input type="button" value="Delete" onClick="location='delete'" class="button error">
                <input type="button" value="Cancel" onClick="location='../'" class="button dark">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

web/tv/templates/tv/control/channels/list.html
{% extends "tv/control/base.html" %}

{% block content %}

<div class="row is-vertical-align">
    <div class="col-3">
        <h3>Channels</h3>
    </div>
    <div class="col-3 is-right">
        <input type="button" value="Add channel ..." onClick="location='new'" class="button primary">
    </div>
</div>

{% if channels %}
{% for channel in channels %}
<div class="row">
    <div class="col-6 is-marginless">
        <div id="channel-{{ channel.pk }}" class="card server-card is-full-width">
            <b><a href="{{ channel.pk }}/">{{ channel }}</a></b>
            <hr>
            <div class="row">
                <div class="col is-marginless">
                    <table>
                        <tr>
                            <td>Source</td>
                            <td><a href="{{ channel.source }}" target="_blank">{{ channel.source }}</a></td>
                        </tr>
                        <tr>
                            <td>Source Type</td>
                            <td>{{ channel.source_type }}</a></td>
                        </tr>
                        <tr>
                            <td>Codec Options</td>
                            <td>{{ channel.get_codec_display }}</a></td>
                        </tr>
                        <tr>
                            <td>Server</td>
                            <td><a href="/control/servers/{{ channel.server.pk }}">{{ channel.server }}</a></td>
                        </tr>
                        <tr>
                            <td>Status</td>
                            <td>
                                {% if channel.container.status|title == "Running" %}
                                <span class="text-success">
                                    {{ channel.container.status|title }}
                                </span><br>
                                {% endif %}
                                {% if channel.container.status|title == "Exited" %}
                                <span class="text-error">
                                    {{ channel.container.status|title }}
                                </span>
                                <br>
                                {% endif %}
                                {% if not channel.container.status %}
                                <span class="text-error">
                                    Not Found
                                </span>
                                <br>
                                {% endif %}
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="col-1 is-marginless">
                    <img class="logo" src="{{ channel.logo.url }}">
                </div>
            </div>
            <div class="col is-full-width is-right">
                {% if channel.container.status != "running" %}
                <input type="button" value="Start" onClick="location='./{{ channel.pk }}/start'" class="button success">
                {% else %}
                <input type="button" value="Restart" onClick="location='./{{ channel.pk }}/restart'"
                    class="button primary">
                <input type="button" value="Stop" onClick="location='./{{ channel.pk }}/stop'" class="button error">
                <input type="button" value="Test" onClick="location='./{{ channel.pk }}/test'" class="button dark">
                {% endif %}
                <input type="button" value="Edit" onClick="location='./{{ channel.pk }}'"
                    class="button primary outline">
                <input type="button" value="Rebuild" onClick="location='./{{ channel.pk }}/recreate'"
                    class="button primary">
                <input type="button" value="Delete" onClick="location='./{{ channel.pk }}/delete'" class="button error">
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}

{% endblock content %}